### ISSUE TITLE
Use client to capture exceptions?

### ISSUE THREAD

**Issue by jhhayashi** [exponent/sentry-utils#10]
Looks like the client has a method for logging warnings (via `Raven.captureMessage()`), but not for capturing exceptions. Should we be using this method for capturing exceptions as well, or should we be using `Raven.captureException()` directly?

~~I'm also happy to write a `logException()` method~~ I added a `logException()` method in https://github.com/expo/sentry-utils/pull/9 that could also be used.

**Comment by brentvatne** [comment]
RIP sentry-utils, long live sentry-expo! https://github.com/expo/sentry-expo
