### ISSUE TITLE
Delete existing Sentry release?

### ISSUE THREAD

**Issue by 7ynk3r** [exponent/sentry-utils#12]
Hi expo team,

I find `publish-sentry-release` really handy but I'm kind of confuse about platform and "Delete existing Sentry release?" logic.

`publish-sentry-release` requires a platform as one the the arguments, which makes sense because the bundle for ios can be different to the one for android.

So I was trying to upload a bundle per platform but I got prompted with "Delete existing Sentry release?" whenever I try to upload the second one.

Looking at the logic that checks for existing bundles, it doesn't have platform as a parameter.
```
  local releaseStatusCode=$(curl -o /dev/null --silent --write-out '%{http_code}' -H "Authorization: Bearer $SENTRY_AUTH_TOKEN" "https://app.getsentry.com/api/0/projects/$SENTRY_TEAM/$SENTRY_PROJECT/releases/$RELEASE_ID/")
```

This makes me wonder, which is the correct way to upload bundles per platform? Am I doing something wrong? 

Thanks in advance,
JM

**Comment by anp** [comment]
cc @nikki93

**Comment by brentvatne** [comment]
Hello! We have released first-class support for Sentry in Expo now, it's very easy to setup and works great. Check out the blog post with a link to the docs here: https://blog.expo.io/easily-integrate-expo-projects-with-sentry-for-error-reporting-8e47d8c2aa51
