### ISSUE TITLE
Unexpected token: punc ({) [./~/@exponent/sentry-utils/index.js:3,0]

### ISSUE THREAD

**Issue by FDiskas** [exponent/sentry-utils#5]
To reproduce:

1.  `npm install create-react-app -g`
1. `create-react-app demo`
1. `cd demo && npm install @exponent/sentry-utils`
1. Add  to `src/App.js`
   ```
   import ExponentSentryClient from '@exponentjs/sentry-utils';
   ExponentSentryClient.setupSentry([SENTRY DSN], [RELEASE], [EXPERIENCE ENTRY FILE]);
   ```
1. `npm run build`

**Comment by FiberJW** [comment]
This module is for Exponent, a superset of React Native, not React. You need to be running an Exponent app for this to work. `create-react-app` is for React on the web.

**Comment by FDiskas** [comment]
:accept:
